import path from 'node:path';
import { disk } from '../storage/index.mjs';
import { paths, workspaceDir, listRounds, readJSON } from '../workspace.mjs';
import { validateContent } from '../protocol/schema.mjs';
import { visibleBlocksForIdentity } from './visibility.mjs';

function safeUploadStem(value) { const raw = typeof value === 'string' ? value : 'file'; const basename = path.posix.basename(raw.replaceAll('\\', '/')); const extension = path.posix.extname(basename); const stem = basename.slice(0, Math.max(0, basename.length - extension.length)); return stem.normalize('NFKD').toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '') || 'file'; }
export function writeAttachment(session, originalName, extension, body) { const uploadsDir = path.resolve(workspaceDir(), session, 'assets', 'uploads'); disk.mkdirSync(uploadsDir, { recursive: true }); const stem = safeUploadStem(originalName); let timestamp = Date.now(); for (;;) { const filename = `${stem}-${timestamp}${extension}`; try { disk.writeFileSync(path.join(uploadsDir, filename), body, { flag: 'wx' }); return filename; } catch (error) { if (error?.code !== 'EEXIST') throw error; timestamp += 1; } } }
function assetUrl(session, relativePath) { return `/assets/${encodeURIComponent(session)}/${relativePath.split('/').map(encodeURIComponent).join('/')}`; }
export function normalizeAssetSubpath(value) { if (typeof value !== 'string' || !value || value.includes('\0')) return null; const normalized = path.posix.normalize(value); return !normalized || normalized === '.' || normalized.startsWith('../') || normalized.startsWith('/') ? null : normalized; }
function readValidContent(session, round) { const content = readJSON(paths.content(session, round, { exactSession: true }), null); return validateContent(content).ok && content.session === session && content.round === round ? content : null; }
const visibilityCache = new Map(); const inventoryCache = new Map();
function fileVersion(target) { try { const stat = disk.lstatSync(target, { bigint: true }); return [stat.dev, stat.ino, stat.size, stat.mtimeNs, stat.mode].join(':'); } catch (error) { return `missing:${error?.code || 'unknown'}`; } }
function cachePut(cache, key, value, limit) { cache.delete(key); cache.set(key, value); while (cache.size > limit) cache.delete(cache.keys().next().value); return value; }
function trimCandidate(value) { let candidate = value; while (candidate && /[).,\]}]+$/.test(candidate)) candidate = candidate.slice(0, -1); return candidate; }
function candidates(value) { const result = []; for (let index = 0; index < value.length;) { const lower = value.slice(index, index + 8).toLowerCase(); if (!lower.startsWith('http://') && !lower.startsWith('https://') && !value.startsWith('/assets/', index)) { index += 1; continue; } let end = index; while (end < value.length && !' \t\r\n"\'<>'.includes(value[end])) end += 1; const candidate = trimCandidate(value.slice(index, end)); if (candidate) result.push(candidate); index = Math.max(end, index + 1); } return result; }
function pathFromCandidate(candidate, session, serviceOrigin) { const lower = candidate.slice(0, 8).toLowerCase(); if (!candidate.startsWith('/assets/') && !lower.startsWith('http://') && !lower.startsWith('https://')) return null; try { const parsed = new URL(candidate, serviceOrigin); if (parsed.origin !== new URL(serviceOrigin).origin || !parsed.pathname.startsWith('/assets/')) return null; const rel = decodeURIComponent(parsed.pathname.slice('/assets/'.length)); const slash = rel.indexOf('/'); return slash <= 0 || rel.slice(0, slash) !== session ? null : normalizeAssetSubpath(rel.slice(slash + 1)); } catch { return null; } }
function collectPaths(value, session, target, origin) { if (typeof value === 'string') { for (const candidate of candidates(value)) { const normalized = pathFromCandidate(candidate, session, origin); if (normalized) target.add(normalized); } } else if (Array.isArray(value)) value.forEach((item) => collectPaths(item, session, target, origin)); else if (value && typeof value === 'object') Object.values(value).forEach((item) => collectPaths(item, session, target, origin)); }
export function visibleAssetPathsForIdentity(session, identity, requestedRound = null, serviceOrigin = 'http://localhost') { if (identity?.role !== 'participant') return null; const round = requestedRound ?? listRounds(session, { exactSession: true }).at(-1) ?? 0; if (!round) return new Set(); const version = fileVersion(paths.content(session, round, { exactSession: true })); let origin; try { origin = new URL(serviceOrigin).origin; } catch { return new Set(); } const key = [session, identity.id || '', round, origin].join('\0'); const cached = visibilityCache.get(key); if (cached?.version === version) return cached.paths; const allowed = new Set(); const content = readValidContent(session, round); if (Array.isArray(content?.blocks)) for (const block of visibleBlocksForIdentity(content.blocks, identity)) collectPaths(block, session, allowed, origin); return cachePut(visibilityCache, key, { version, paths: allowed }, 512).paths; }
function inventoryValid(cached) { return cached?.directories?.every(([directory, version]) => fileVersion(directory) === version) && cached?.fileVersions?.every(([relativePath, version]) => fileVersion(path.join(cached.root, relativePath)) === version); }
export function listSessionAssets(session, allowedPaths = null) { const root = path.resolve(workspaceDir(), session, 'assets'); const version = fileVersion(root); const cached = inventoryCache.get(root); if (cached?.version === version && inventoryValid(cached)) return allowedPaths ? cached.files.filter((file) => allowedPaths.has(file.path)) : cached.files; const files = []; const directories = new Map(); function walk(directory, relativeDirectory = '') { directories.set(directory, fileVersion(directory)); for (const entry of disk.readdirSync(directory, { withFileTypes: true }).sort((a, b) => a.name.localeCompare(b.name, 'zh-CN'))) { if (entry.isSymbolicLink()) continue; const relativePath = relativeDirectory ? path.posix.join(relativeDirectory, entry.name) : entry.name; const absolutePath = path.join(directory, entry.name); if (entry.isDirectory()) walk(absolutePath, relativePath); else if (entry.isFile()) { const stat = disk.lstatSync(absolutePath); if (stat.isFile()) files.push({ path: relativePath, url: assetUrl(session, relativePath), size: stat.size }); } } } try { const stat = disk.lstatSync(root); if (stat.isSymbolicLink() || !stat.isDirectory()) return []; walk(root); } catch (error) { if (error?.code === 'ENOENT') return []; throw error; } const cachedFiles = cachePut(inventoryCache, root, { root, version, files, directories: [...directories.entries()], fileVersions: files.map((file) => [file.path, fileVersion(path.join(root, file.path))]) }, 128).files; return allowedPaths ? cachedFiles.filter((file) => allowedPaths.has(file.path)) : cachedFiles; }
function assertNoSymlinkComponents(root, relativePath) { const workspaceRoot = path.resolve(workspaceDir()); const rootRelative = path.relative(workspaceRoot, root); let current = workspaceRoot; for (const component of rootRelative.split(path.sep).filter(Boolean)) { current = path.join(current, component); const stat = disk.lstatSync(current); if (stat.isSymbolicLink() || !stat.isDirectory()) { const error = new Error(stat.isSymbolicLink() ? 'asset path contains a symbolic link' : 'asset path component is not a directory'); error.code = stat.isSymbolicLink() ? 'ASSET_FORBIDDEN' : 'ENOTDIR'; throw error; } } for (const [index, component] of relativePath.split('/').entries()) { current = path.join(current, component); const stat = disk.lstatSync(current); if (stat.isSymbolicLink() || (index < relativePath.split('/').length - 1 && !stat.isDirectory())) { const error = new Error(stat.isSymbolicLink() ? 'asset path contains a symbolic link' : 'asset path component is not a directory'); error.code = stat.isSymbolicLink() ? 'ASSET_FORBIDDEN' : 'ENOTDIR'; throw error; } } }
export function readAssetFile(root, normalizedSub) { const workspaceRoot = disk.realpathSync(workspaceDir()); const realRoot = disk.realpathSync(root); if (!realRoot.startsWith(workspaceRoot + path.sep)) { const error = new Error('asset root outside workspace'); error.code = 'ASSET_FORBIDDEN'; throw error; } assertNoSymlinkComponents(root, normalizedSub); const abs = path.resolve(root, normalizedSub); let fd; try { fd = disk.openSync(abs, disk.constants.O_RDONLY | (disk.constants.O_NOFOLLOW || 0)); const stat = disk.fstatSync(fd); if (!stat.isFile()) { const error = new Error('asset is not a regular file'); error.code = 'ASSET_NOT_FILE'; throw error; } return disk.readFileSync(fd); } catch (error) { if (error?.code === 'ELOOP') error.code = 'ASSET_FORBIDDEN'; throw error; } finally { if (fd != null) try { disk.closeSync(fd); } catch {} } }
export function assetServiceOrigin(req) { const protocol = req.socket.encrypted ? 'https' : 'http'; const address = req.socket.localAddress || '127.0.0.1'; const host = address.includes(':') && !address.startsWith('[') ? `[${address}]` : address; return `${protocol}://${host}${req.socket.localPort ? `:${req.socket.localPort}` : ''}`; }
export function requestOrigin(req) { const forwardedProto = String(req.headers['x-forwarded-proto'] || '').split(',')[0].trim(); const protocol = /^https?$/i.test(forwardedProto) ? forwardedProto.toLowerCase() : (req.socket.encrypted ? 'https' : 'http'); return `${protocol}://${String(req.headers['x-forwarded-host'] || '').split(',')[0].trim() || req.headers.host || '127.0.0.1'}`; }
export function renderUrl(req, session) { let target; try { target = new URL('/render/', requestOrigin(req)); } catch { target = new URL('/render/', 'http://127.0.0.1'); } target.searchParams.set('session', session); return target.href; }
